site_name: Reliafy CLI
site_url: !ENV [SITE_URL, https://reliafy.app]
repo_url: https://github.com/CarrascoCesar/Reliafy-CLI
repo_name: !ENV [RELIAFY_DOCS_REPO_NAME, GitHub]
hooks:
  - docs/hooks.py
copyright: Copyright &copy; 2026 Reliafy. All rights reserved. Copyright registration pending.
theme:
  name: material
  custom_dir: overrides
  logo: Reliafy logo.png
  favicon: Reliafy favicon 32x32.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    # - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.follow
extra:
  math:
    provider: mathjax
nav:
  - Home: index.md
  - Packaged Examples: examples.md
  - CLI Commands:
    - CLI Basics for Reliafy Users: cli/basics.md
    - Command Overview: cli/command-overview.md
    - Analyze: cli/analyze.md
    - Design: cli/design.md
    - Simulate: cli/simulate.md
    - Result Files: cli/results-files.md
  - Profiles:
    - Profile Management: profiles/index.md
    - Profile Options Reference: profiles/profile-reference.md
  - Problem Definition:
    - Overview: problem-authoring/index.md
    - Analyze:
      - FORM Only: problem-authoring/analyze/form-only.md
      - SORM and Monte Carlo: problem-authoring/analyze/sorm-monte-carlo.md
    - Design:
      - Overview: problem-authoring/design/index.md
      - Design Keys Reference: problem-authoring/design/design-keys.md
      - Inverse FORM Examples: problem-authoring/design/inverse-form.md
      - Objective Optimization Example: problem-authoring/design/optimization.md
    - Simulate:
      - Classic Monte Carlo: problem-authoring/simulate/classic-monte-carlo.md
      - Importance Sampling: problem-authoring/simulate/importance-sampling.md
    - Recommended Texts and References: problem-authoring/recommended-texts.md
  - Software References:
    - Overview: software-references.md
    - CLI Dependencies and Citations: software-references-cli.md
    - API Library Credits: software-references-api.md
  - User Authentication: auth.md
markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
extra_css:
  - stylesheets/extra.css
